# Website info
name: 'Eat. Code. Skydive.'
description: "It's one thing to write code. It's another to humanize<br>technology so it serves a purpose in people's lives.<br>&mdash; Luke Wroblewski"
logo: 'ğŸ´ ğŸ’» ğŸš'

# Author's info
author: 'Adam Tuttle'
username: adam
bio: 'A skydiving bum trapped in a working man''s body'
location: 'Pennsylvania, USA'
url: 'http://github.com/atuttle/blog/'
image: 'assets/images/adam@2x.jpg'

# Jykell configuration
markdown: redcarpet
highlighter: pygments
paginate: 10
language: 'en-us'
short_url: 'github.com/atuttle/blog'
google_analytics: 'todo'
disqus: username
baseurl: /
fullurl: 'http://adamtuttle.codes/'
link_base: ''

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...
